// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainConfig = "chain_config"

// ChainConfig mapped from table <chain_config>
type ChainConfig struct {
	Chain            string    `gorm:"column:chain;type:TEXT" json:"chain"`
	ChainID          int32     `gorm:"column:chain_id;type:INTEGER" json:"chain_id"`
	ChainType        string    `gorm:"column:chain_type;type:TEXT" json:"chain_type"`
	Currency         string    `gorm:"column:currency;type:TEXT" json:"currency"`
	Multicall3       string    `gorm:"column:multicall3;type:TEXT" json:"multicall3"`
	ExplorerUrl      string    `gorm:"column:explorer_url;type:TEXT" json:"explorer_url"`
	ExplorerTxPath   string    `gorm:"column:explorer_tx_path;type:TEXT" json:"explorer_tx_path"`
	ExplorerAddrPath string    `gorm:"column:explorer_addr_path;type:TEXT" json:"explorer_addr_path"`
	CreatedAt        time.Time `gorm:"column:created_at;type:TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:TIMESTAMP" json:"updated_at"`
}

// TableName ChainConfig's table name
func (*ChainConfig) TableName() string {
	return TableNameChainConfig
}
