// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMerchantWallet = "merchant_wallet"

// MerchantWallet mapped from table <merchant_wallet>
type MerchantWallet struct {
	Address   string    `gorm:"column:address;type:TEXT" json:"address"`
	ChainType string    `gorm:"column:chain_type;type:TEXT" json:"chain_type"`
	EncKey    string    `gorm:"column:enc_key;type:TEXT" json:"enc_key"`
	IsDefault bool      `gorm:"column:is_default;type:BOOLEAN" json:"is_default"`
	CreatedAt time.Time `gorm:"column:created_at;type:TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:TIMESTAMP" json:"updated_at"`
}

// TableName MerchantWallet's table name
func (*MerchantWallet) TableName() string {
	return TableNameMerchantWallet
}
