// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePasswordAuth = "password_auth"

// PasswordAuth mapped from table <password_auth>
type PasswordAuth struct {
	ID        int32     `gorm:"column:id;type:INTEGER" json:"id"`
	Salt      []byte    `gorm:"column:salt;type:BLOB" json:"salt"`
	Hash      []byte    `gorm:"column:hash;type:BLOB" json:"hash"`
	CreatedAt time.Time `gorm:"column:created_at;type:DATETIME" json:"created_at"`
}

// TableName PasswordAuth's table name
func (*PasswordAuth) TableName() string {
	return TableNamePasswordAuth
}
