// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReceiptAddress = "receipt_address"

// ReceiptAddress mapped from table <receipt_address>
type ReceiptAddress struct {
	Address     string    `gorm:"column:address;type:TEXT" json:"address"`
	Splitter    string    `gorm:"column:splitter;type:TEXT" json:"splitter"`
	Chain       string    `gorm:"column:chain;type:TEXT" json:"chain"`
	Curve       string    `gorm:"column:curve;type:TEXT" json:"curve"`
	KeyFromData []byte    `gorm:"column:key_from_data;type:BLOB" json:"key_from_data"`
	PubKeyData  []byte    `gorm:"column:pub_key_data" json:"pub_key_data"`
	CreatedAt   time.Time `gorm:"column:created_at;type:TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:TIMESTAMP" json:"updated_at"`
}

// TableName ReceiptAddress's table name
func (*ReceiptAddress) TableName() string {
	return TableNameReceiptAddress
}
