// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRPCEndpoint = "rpc_endpoint"

// RPCEndpoint mapped from table <rpc_endpoint>
type RPCEndpoint struct {
	Chain    string    `gorm:"column:chain;type:TEXT" json:"chain"`
	Provider string    `gorm:"column:provider;type:TEXT" json:"provider"`
	Endpoint string    `gorm:"column:endpoint;type:TEXT" json:"endpoint"`
	APIKey   string    `gorm:"column:api_key;type:TEXT" json:"api_key"`
	CreatedAt time.Time `gorm:"column:created_at;type:TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RPCEndpoint's table name
func (*RPCEndpoint) TableName() string {
	return TableNameRPCEndpoint
}
