// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSplitWallet = "split_wallet"

// SplitWallet mapped from table <split_wallet>
type SplitWallet struct {
	Address            string    `gorm:"column:address;primaryKey;type:TEXT" json:"address"`
	Chain              string    `gorm:"column:chain;type:TEXT" json:"chain"`
	Merchant           string    `gorm:"column:merchant;type:TEXT" json:"merchant"`
	Alias              string    `gorm:"column:alias;type:TEXT" json:"alias"`
	SplitWalletManager string    `gorm:"column:split_wallet_manager;type:TEXT" json:"split_wallet_manager"`
	State              int       `gorm:"column:state;type:INTEGER" json:"state"`
	ActivateTxID       string    `gorm:"column:activate_tx_id;type:TEXT" json:"activate_tx_id"`
	ProxyAdmin         string    `gorm:"column:proxy_admin;type:TEXT" json:"proxy_admin"`
	CreatedAt          time.Time `gorm:"column:created_at;type:TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at;type:TIMESTAMP" json:"updated_at"`
}

// TableName SplitWallet's table name
func (*SplitWallet) TableName() string {
	return TableNameSplitWallet
}
