// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTokenConfig = "token_config"

// TokenConfig mapped from table <token_config>
type TokenConfig struct {
	Symbol    string    `gorm:"column:symbol;primaryKey" json:"symbol"`
	Chain     string    `gorm:"column:chain;not null" json:"chain"`
	Contract  string    `gorm:"column:contract;type:TEXT" json:"contract"`
	Name      string    `gorm:"column:name;type:TEXT" json:"name"`
	CreatedAt time.Time `gorm:"column:created_at;type:TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TokenConfig's table name
func (*TokenConfig) TableName() string {
	return TableNameTokenConfig
}
