// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"hashnut-mpc-client/storage/dal/model"
)

func newChainConfig(db *gorm.DB, opts ...gen.DOOption) chainConfig {
	_chainConfig := chainConfig{}

	_chainConfig.chainConfigDo.UseDB(db, opts...)
	_chainConfig.chainConfigDo.UseModel(&model.ChainConfig{})

	tableName := _chainConfig.chainConfigDo.TableName()
	_chainConfig.ALL = field.NewAsterisk(tableName)
	_chainConfig.Chain = field.NewString(tableName, "chain")
	_chainConfig.ChainID = field.NewInt32(tableName, "chain_id")
	_chainConfig.ChainType = field.NewString(tableName, "chain_type")
	_chainConfig.Currency = field.NewString(tableName, "currency")
	_chainConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_chainConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_chainConfig.fillFieldMap()

	return _chainConfig
}

type chainConfig struct {
	chainConfigDo chainConfigDo

	ALL       field.Asterisk
	Chain     field.String
	ChainID   field.Int32
	ChainType field.String
	Currency  field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c chainConfig) Table(newTableName string) *chainConfig {
	c.chainConfigDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chainConfig) As(alias string) *chainConfig {
	c.chainConfigDo.DO = *(c.chainConfigDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chainConfig) updateTableName(table string) *chainConfig {
	c.ALL = field.NewAsterisk(table)
	c.Chain = field.NewString(table, "chain")
	c.ChainID = field.NewInt32(table, "chain_id")
	c.ChainType = field.NewString(table, "chain_type")
	c.Currency = field.NewString(table, "currency")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *chainConfig) WithContext(ctx context.Context) IChainConfigDo {
	return c.chainConfigDo.WithContext(ctx)
}

func (c chainConfig) TableName() string { return c.chainConfigDo.TableName() }

func (c chainConfig) Alias() string { return c.chainConfigDo.Alias() }

func (c chainConfig) Columns(cols ...field.Expr) gen.Columns { return c.chainConfigDo.Columns(cols...) }

func (c *chainConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chainConfig) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["chain"] = c.Chain
	c.fieldMap["chain_id"] = c.ChainID
	c.fieldMap["chain_type"] = c.ChainType
	c.fieldMap["currency"] = c.Currency
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c chainConfig) clone(db *gorm.DB) chainConfig {
	c.chainConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chainConfig) replaceDB(db *gorm.DB) chainConfig {
	c.chainConfigDo.ReplaceDB(db)
	return c
}

type chainConfigDo struct{ gen.DO }

type IChainConfigDo interface {
	gen.SubQuery
	Debug() IChainConfigDo
	WithContext(ctx context.Context) IChainConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChainConfigDo
	WriteDB() IChainConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChainConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChainConfigDo
	Not(conds ...gen.Condition) IChainConfigDo
	Or(conds ...gen.Condition) IChainConfigDo
	Select(conds ...field.Expr) IChainConfigDo
	Where(conds ...gen.Condition) IChainConfigDo
	Order(conds ...field.Expr) IChainConfigDo
	Distinct(cols ...field.Expr) IChainConfigDo
	Omit(cols ...field.Expr) IChainConfigDo
	Join(table schema.Tabler, on ...field.Expr) IChainConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChainConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChainConfigDo
	Group(cols ...field.Expr) IChainConfigDo
	Having(conds ...gen.Condition) IChainConfigDo
	Limit(limit int) IChainConfigDo
	Offset(offset int) IChainConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChainConfigDo
	Unscoped() IChainConfigDo
	Create(values ...*model.ChainConfig) error
	CreateInBatches(values []*model.ChainConfig, batchSize int) error
	Save(values ...*model.ChainConfig) error
	First() (*model.ChainConfig, error)
	Take() (*model.ChainConfig, error)
	Last() (*model.ChainConfig, error)
	Find() ([]*model.ChainConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChainConfig, err error)
	FindInBatches(result *[]*model.ChainConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChainConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChainConfigDo
	Assign(attrs ...field.AssignExpr) IChainConfigDo
	Joins(fields ...field.RelationField) IChainConfigDo
	Preload(fields ...field.RelationField) IChainConfigDo
	FirstOrInit() (*model.ChainConfig, error)
	FirstOrCreate() (*model.ChainConfig, error)
	FindByPage(offset int, limit int) (result []*model.ChainConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChainConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chainConfigDo) Debug() IChainConfigDo {
	return c.withDO(c.DO.Debug())
}

func (c chainConfigDo) WithContext(ctx context.Context) IChainConfigDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chainConfigDo) ReadDB() IChainConfigDo {
	return c.Clauses(dbresolver.Read)
}

func (c chainConfigDo) WriteDB() IChainConfigDo {
	return c.Clauses(dbresolver.Write)
}

func (c chainConfigDo) Session(config *gorm.Session) IChainConfigDo {
	return c.withDO(c.DO.Session(config))
}

func (c chainConfigDo) Clauses(conds ...clause.Expression) IChainConfigDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chainConfigDo) Returning(value interface{}, columns ...string) IChainConfigDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chainConfigDo) Not(conds ...gen.Condition) IChainConfigDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chainConfigDo) Or(conds ...gen.Condition) IChainConfigDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chainConfigDo) Select(conds ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chainConfigDo) Where(conds ...gen.Condition) IChainConfigDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chainConfigDo) Order(conds ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chainConfigDo) Distinct(cols ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chainConfigDo) Omit(cols ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chainConfigDo) Join(table schema.Tabler, on ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chainConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chainConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chainConfigDo) Group(cols ...field.Expr) IChainConfigDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chainConfigDo) Having(conds ...gen.Condition) IChainConfigDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chainConfigDo) Limit(limit int) IChainConfigDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chainConfigDo) Offset(offset int) IChainConfigDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chainConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChainConfigDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chainConfigDo) Unscoped() IChainConfigDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chainConfigDo) Create(values ...*model.ChainConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chainConfigDo) CreateInBatches(values []*model.ChainConfig, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chainConfigDo) Save(values ...*model.ChainConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chainConfigDo) First() (*model.ChainConfig, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChainConfig), nil
	}
}

func (c chainConfigDo) Take() (*model.ChainConfig, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChainConfig), nil
	}
}

func (c chainConfigDo) Last() (*model.ChainConfig, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChainConfig), nil
	}
}

func (c chainConfigDo) Find() ([]*model.ChainConfig, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChainConfig), err
}

func (c chainConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChainConfig, err error) {
	buf := make([]*model.ChainConfig, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chainConfigDo) FindInBatches(result *[]*model.ChainConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chainConfigDo) Attrs(attrs ...field.AssignExpr) IChainConfigDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chainConfigDo) Assign(attrs ...field.AssignExpr) IChainConfigDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chainConfigDo) Joins(fields ...field.RelationField) IChainConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chainConfigDo) Preload(fields ...field.RelationField) IChainConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chainConfigDo) FirstOrInit() (*model.ChainConfig, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChainConfig), nil
	}
}

func (c chainConfigDo) FirstOrCreate() (*model.ChainConfig, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChainConfig), nil
	}
}

func (c chainConfigDo) FindByPage(offset int, limit int) (result []*model.ChainConfig, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chainConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chainConfigDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chainConfigDo) Delete(models ...*model.ChainConfig) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chainConfigDo) withDO(do gen.Dao) *chainConfigDo {
	c.DO = *do.(*gen.DO)
	return c
}
