// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	ChainConfig    *chainConfig
	MerchantWallet *merchantWallet

	PasswordAuth   *passwordAuth
	RPCEndpoint    *rPCEndpoint
	ReceiptAddress *receiptAddress
	SplitWallet    *splitWallet
	TokenConfig    *tokenConfig
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ChainConfig = &Q.ChainConfig
	MerchantWallet = &Q.MerchantWallet

	PasswordAuth = &Q.PasswordAuth
	RPCEndpoint = &Q.RPCEndpoint
	ReceiptAddress = &Q.ReceiptAddress
	SplitWallet = &Q.SplitWallet
	TokenConfig = &Q.TokenConfig
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		ChainConfig:    newChainConfig(db, opts...),
		MerchantWallet: newMerchantWallet(db, opts...),

		PasswordAuth:   newPasswordAuth(db, opts...),
		RPCEndpoint:    newRPCEndpoint(db, opts...),
		ReceiptAddress: newReceiptAddress(db, opts...),
		SplitWallet:    newSplitWallet(db, opts...),
		TokenConfig:    newTokenConfig(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ChainConfig    chainConfig
	MerchantWallet merchantWallet

	PasswordAuth   passwordAuth
	RPCEndpoint    rPCEndpoint
	ReceiptAddress receiptAddress
	SplitWallet    splitWallet
	TokenConfig    tokenConfig
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		ChainConfig:    q.ChainConfig.clone(db),
		MerchantWallet: q.MerchantWallet.clone(db),

		PasswordAuth:   q.PasswordAuth.clone(db),
		RPCEndpoint:    q.RPCEndpoint.clone(db),
		ReceiptAddress: q.ReceiptAddress.clone(db),
		SplitWallet:    q.SplitWallet.clone(db),
		TokenConfig:    q.TokenConfig.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		ChainConfig:    q.ChainConfig.replaceDB(db),
		MerchantWallet: q.MerchantWallet.replaceDB(db),

		PasswordAuth:   q.PasswordAuth.replaceDB(db),
		RPCEndpoint:    q.RPCEndpoint.replaceDB(db),
		ReceiptAddress: q.ReceiptAddress.replaceDB(db),
		SplitWallet:    q.SplitWallet.replaceDB(db),
		TokenConfig:    q.TokenConfig.replaceDB(db),
	}
}

type queryCtx struct {
	ChainConfig    IChainConfigDo
	MerchantWallet IMerchantWalletDo

	PasswordAuth   IPasswordAuthDo
	RPCEndpoint    IRPCEndpointDo
	ReceiptAddress IReceiptAddressDo
	SplitWallet    ISplitWalletDo
	TokenConfig    ITokenConfigDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ChainConfig:    q.ChainConfig.WithContext(ctx),
		MerchantWallet: q.MerchantWallet.WithContext(ctx),

		PasswordAuth:   q.PasswordAuth.WithContext(ctx),
		RPCEndpoint:    q.RPCEndpoint.WithContext(ctx),
		ReceiptAddress: q.ReceiptAddress.WithContext(ctx),
		SplitWallet:    q.SplitWallet.WithContext(ctx),
		TokenConfig:    q.TokenConfig.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
