// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"hashnut-mpc-client/storage/dal/model"
)

func newMerchantWallet(db *gorm.DB, opts ...gen.DOOption) merchantWallet {
	_merchantWallet := merchantWallet{}

	_merchantWallet.merchantWalletDo.UseDB(db, opts...)
	_merchantWallet.merchantWalletDo.UseModel(&model.MerchantWallet{})

	tableName := _merchantWallet.merchantWalletDo.TableName()
	_merchantWallet.ALL = field.NewAsterisk(tableName)
	_merchantWallet.Address = field.NewString(tableName, "address")
	_merchantWallet.ChainType = field.NewString(tableName, "chain_type")
	_merchantWallet.EncKey = field.NewString(tableName, "enc_key")
	_merchantWallet.IsDefault = field.NewBool(tableName, "is_default")
	_merchantWallet.CreatedAt = field.NewTime(tableName, "created_at")
	_merchantWallet.UpdatedAt = field.NewTime(tableName, "updated_at")

	_merchantWallet.fillFieldMap()

	return _merchantWallet
}

type merchantWallet struct {
	merchantWalletDo merchantWalletDo

	ALL       field.Asterisk
	Address   field.String
	ChainType field.String
	EncKey    field.String
	IsDefault field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (m merchantWallet) Table(newTableName string) *merchantWallet {
	m.merchantWalletDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m merchantWallet) As(alias string) *merchantWallet {
	m.merchantWalletDo.DO = *(m.merchantWalletDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *merchantWallet) updateTableName(table string) *merchantWallet {
	m.ALL = field.NewAsterisk(table)
	m.Address = field.NewString(table, "address")
	m.ChainType = field.NewString(table, "chain_type")
	m.EncKey = field.NewString(table, "enc_key")
	m.IsDefault = field.NewBool(table, "is_default")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *merchantWallet) WithContext(ctx context.Context) IMerchantWalletDo {
	return m.merchantWalletDo.WithContext(ctx)
}

func (m merchantWallet) TableName() string { return m.merchantWalletDo.TableName() }

func (m merchantWallet) Alias() string { return m.merchantWalletDo.Alias() }

func (m merchantWallet) Columns(cols ...field.Expr) gen.Columns {
	return m.merchantWalletDo.Columns(cols...)
}

func (m *merchantWallet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *merchantWallet) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["address"] = m.Address
	m.fieldMap["chain_type"] = m.ChainType
	m.fieldMap["enc_key"] = m.EncKey
	m.fieldMap["is_default"] = m.IsDefault
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m merchantWallet) clone(db *gorm.DB) merchantWallet {
	m.merchantWalletDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m merchantWallet) replaceDB(db *gorm.DB) merchantWallet {
	m.merchantWalletDo.ReplaceDB(db)
	return m
}

type merchantWalletDo struct{ gen.DO }

type IMerchantWalletDo interface {
	gen.SubQuery
	Debug() IMerchantWalletDo
	WithContext(ctx context.Context) IMerchantWalletDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMerchantWalletDo
	WriteDB() IMerchantWalletDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMerchantWalletDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMerchantWalletDo
	Not(conds ...gen.Condition) IMerchantWalletDo
	Or(conds ...gen.Condition) IMerchantWalletDo
	Select(conds ...field.Expr) IMerchantWalletDo
	Where(conds ...gen.Condition) IMerchantWalletDo
	Order(conds ...field.Expr) IMerchantWalletDo
	Distinct(cols ...field.Expr) IMerchantWalletDo
	Omit(cols ...field.Expr) IMerchantWalletDo
	Join(table schema.Tabler, on ...field.Expr) IMerchantWalletDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMerchantWalletDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMerchantWalletDo
	Group(cols ...field.Expr) IMerchantWalletDo
	Having(conds ...gen.Condition) IMerchantWalletDo
	Limit(limit int) IMerchantWalletDo
	Offset(offset int) IMerchantWalletDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMerchantWalletDo
	Unscoped() IMerchantWalletDo
	Create(values ...*model.MerchantWallet) error
	CreateInBatches(values []*model.MerchantWallet, batchSize int) error
	Save(values ...*model.MerchantWallet) error
	First() (*model.MerchantWallet, error)
	Take() (*model.MerchantWallet, error)
	Last() (*model.MerchantWallet, error)
	Find() ([]*model.MerchantWallet, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerchantWallet, err error)
	FindInBatches(result *[]*model.MerchantWallet, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MerchantWallet) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMerchantWalletDo
	Assign(attrs ...field.AssignExpr) IMerchantWalletDo
	Joins(fields ...field.RelationField) IMerchantWalletDo
	Preload(fields ...field.RelationField) IMerchantWalletDo
	FirstOrInit() (*model.MerchantWallet, error)
	FirstOrCreate() (*model.MerchantWallet, error)
	FindByPage(offset int, limit int) (result []*model.MerchantWallet, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMerchantWalletDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m merchantWalletDo) Debug() IMerchantWalletDo {
	return m.withDO(m.DO.Debug())
}

func (m merchantWalletDo) WithContext(ctx context.Context) IMerchantWalletDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m merchantWalletDo) ReadDB() IMerchantWalletDo {
	return m.Clauses(dbresolver.Read)
}

func (m merchantWalletDo) WriteDB() IMerchantWalletDo {
	return m.Clauses(dbresolver.Write)
}

func (m merchantWalletDo) Session(config *gorm.Session) IMerchantWalletDo {
	return m.withDO(m.DO.Session(config))
}

func (m merchantWalletDo) Clauses(conds ...clause.Expression) IMerchantWalletDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m merchantWalletDo) Returning(value interface{}, columns ...string) IMerchantWalletDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m merchantWalletDo) Not(conds ...gen.Condition) IMerchantWalletDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m merchantWalletDo) Or(conds ...gen.Condition) IMerchantWalletDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m merchantWalletDo) Select(conds ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m merchantWalletDo) Where(conds ...gen.Condition) IMerchantWalletDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m merchantWalletDo) Order(conds ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m merchantWalletDo) Distinct(cols ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m merchantWalletDo) Omit(cols ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m merchantWalletDo) Join(table schema.Tabler, on ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m merchantWalletDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m merchantWalletDo) RightJoin(table schema.Tabler, on ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m merchantWalletDo) Group(cols ...field.Expr) IMerchantWalletDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m merchantWalletDo) Having(conds ...gen.Condition) IMerchantWalletDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m merchantWalletDo) Limit(limit int) IMerchantWalletDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m merchantWalletDo) Offset(offset int) IMerchantWalletDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m merchantWalletDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMerchantWalletDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m merchantWalletDo) Unscoped() IMerchantWalletDo {
	return m.withDO(m.DO.Unscoped())
}

func (m merchantWalletDo) Create(values ...*model.MerchantWallet) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m merchantWalletDo) CreateInBatches(values []*model.MerchantWallet, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m merchantWalletDo) Save(values ...*model.MerchantWallet) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m merchantWalletDo) First() (*model.MerchantWallet, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantWallet), nil
	}
}

func (m merchantWalletDo) Take() (*model.MerchantWallet, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantWallet), nil
	}
}

func (m merchantWalletDo) Last() (*model.MerchantWallet, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantWallet), nil
	}
}

func (m merchantWalletDo) Find() ([]*model.MerchantWallet, error) {
	result, err := m.DO.Find()
	return result.([]*model.MerchantWallet), err
}

func (m merchantWalletDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerchantWallet, err error) {
	buf := make([]*model.MerchantWallet, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m merchantWalletDo) FindInBatches(result *[]*model.MerchantWallet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m merchantWalletDo) Attrs(attrs ...field.AssignExpr) IMerchantWalletDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m merchantWalletDo) Assign(attrs ...field.AssignExpr) IMerchantWalletDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m merchantWalletDo) Joins(fields ...field.RelationField) IMerchantWalletDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m merchantWalletDo) Preload(fields ...field.RelationField) IMerchantWalletDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m merchantWalletDo) FirstOrInit() (*model.MerchantWallet, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantWallet), nil
	}
}

func (m merchantWalletDo) FirstOrCreate() (*model.MerchantWallet, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerchantWallet), nil
	}
}

func (m merchantWalletDo) FindByPage(offset int, limit int) (result []*model.MerchantWallet, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m merchantWalletDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m merchantWalletDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m merchantWalletDo) Delete(models ...*model.MerchantWallet) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *merchantWalletDo) withDO(do gen.Dao) *merchantWalletDo {
	m.DO = *do.(*gen.DO)
	return m
}
