// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"hashnut-mpc-client/storage/dal/model"
)

func newPasswordAuth(db *gorm.DB, opts ...gen.DOOption) passwordAuth {
	_passwordAuth := passwordAuth{}

	_passwordAuth.passwordAuthDo.UseDB(db, opts...)
	_passwordAuth.passwordAuthDo.UseModel(&model.PasswordAuth{})

	tableName := _passwordAuth.passwordAuthDo.TableName()
	_passwordAuth.ALL = field.NewAsterisk(tableName)
	_passwordAuth.ID = field.NewInt32(tableName, "id")
	_passwordAuth.Salt = field.NewBytes(tableName, "salt")
	_passwordAuth.Hash = field.NewBytes(tableName, "hash")
	_passwordAuth.CreatedAt = field.NewTime(tableName, "created_at")

	_passwordAuth.fillFieldMap()

	return _passwordAuth
}

type passwordAuth struct {
	passwordAuthDo passwordAuthDo

	ALL       field.Asterisk
	ID        field.Int32
	Salt      field.Bytes
	Hash      field.Bytes
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p passwordAuth) Table(newTableName string) *passwordAuth {
	p.passwordAuthDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p passwordAuth) As(alias string) *passwordAuth {
	p.passwordAuthDo.DO = *(p.passwordAuthDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *passwordAuth) updateTableName(table string) *passwordAuth {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.Salt = field.NewBytes(table, "salt")
	p.Hash = field.NewBytes(table, "hash")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *passwordAuth) WithContext(ctx context.Context) IPasswordAuthDo {
	return p.passwordAuthDo.WithContext(ctx)
}

func (p passwordAuth) TableName() string { return p.passwordAuthDo.TableName() }

func (p passwordAuth) Alias() string { return p.passwordAuthDo.Alias() }

func (p passwordAuth) Columns(cols ...field.Expr) gen.Columns {
	return p.passwordAuthDo.Columns(cols...)
}

func (p *passwordAuth) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *passwordAuth) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id"] = p.ID
	p.fieldMap["salt"] = p.Salt
	p.fieldMap["hash"] = p.Hash
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p passwordAuth) clone(db *gorm.DB) passwordAuth {
	p.passwordAuthDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p passwordAuth) replaceDB(db *gorm.DB) passwordAuth {
	p.passwordAuthDo.ReplaceDB(db)
	return p
}

type passwordAuthDo struct{ gen.DO }

type IPasswordAuthDo interface {
	gen.SubQuery
	Debug() IPasswordAuthDo
	WithContext(ctx context.Context) IPasswordAuthDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPasswordAuthDo
	WriteDB() IPasswordAuthDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPasswordAuthDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPasswordAuthDo
	Not(conds ...gen.Condition) IPasswordAuthDo
	Or(conds ...gen.Condition) IPasswordAuthDo
	Select(conds ...field.Expr) IPasswordAuthDo
	Where(conds ...gen.Condition) IPasswordAuthDo
	Order(conds ...field.Expr) IPasswordAuthDo
	Distinct(cols ...field.Expr) IPasswordAuthDo
	Omit(cols ...field.Expr) IPasswordAuthDo
	Join(table schema.Tabler, on ...field.Expr) IPasswordAuthDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPasswordAuthDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPasswordAuthDo
	Group(cols ...field.Expr) IPasswordAuthDo
	Having(conds ...gen.Condition) IPasswordAuthDo
	Limit(limit int) IPasswordAuthDo
	Offset(offset int) IPasswordAuthDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPasswordAuthDo
	Unscoped() IPasswordAuthDo
	Create(values ...*model.PasswordAuth) error
	CreateInBatches(values []*model.PasswordAuth, batchSize int) error
	Save(values ...*model.PasswordAuth) error
	First() (*model.PasswordAuth, error)
	Take() (*model.PasswordAuth, error)
	Last() (*model.PasswordAuth, error)
	Find() ([]*model.PasswordAuth, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PasswordAuth, err error)
	FindInBatches(result *[]*model.PasswordAuth, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PasswordAuth) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPasswordAuthDo
	Assign(attrs ...field.AssignExpr) IPasswordAuthDo
	Joins(fields ...field.RelationField) IPasswordAuthDo
	Preload(fields ...field.RelationField) IPasswordAuthDo
	FirstOrInit() (*model.PasswordAuth, error)
	FirstOrCreate() (*model.PasswordAuth, error)
	FindByPage(offset int, limit int) (result []*model.PasswordAuth, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPasswordAuthDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p passwordAuthDo) Debug() IPasswordAuthDo {
	return p.withDO(p.DO.Debug())
}

func (p passwordAuthDo) WithContext(ctx context.Context) IPasswordAuthDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p passwordAuthDo) ReadDB() IPasswordAuthDo {
	return p.Clauses(dbresolver.Read)
}

func (p passwordAuthDo) WriteDB() IPasswordAuthDo {
	return p.Clauses(dbresolver.Write)
}

func (p passwordAuthDo) Session(config *gorm.Session) IPasswordAuthDo {
	return p.withDO(p.DO.Session(config))
}

func (p passwordAuthDo) Clauses(conds ...clause.Expression) IPasswordAuthDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p passwordAuthDo) Returning(value interface{}, columns ...string) IPasswordAuthDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p passwordAuthDo) Not(conds ...gen.Condition) IPasswordAuthDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p passwordAuthDo) Or(conds ...gen.Condition) IPasswordAuthDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p passwordAuthDo) Select(conds ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p passwordAuthDo) Where(conds ...gen.Condition) IPasswordAuthDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p passwordAuthDo) Order(conds ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p passwordAuthDo) Distinct(cols ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p passwordAuthDo) Omit(cols ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p passwordAuthDo) Join(table schema.Tabler, on ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p passwordAuthDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p passwordAuthDo) RightJoin(table schema.Tabler, on ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p passwordAuthDo) Group(cols ...field.Expr) IPasswordAuthDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p passwordAuthDo) Having(conds ...gen.Condition) IPasswordAuthDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p passwordAuthDo) Limit(limit int) IPasswordAuthDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p passwordAuthDo) Offset(offset int) IPasswordAuthDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p passwordAuthDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPasswordAuthDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p passwordAuthDo) Unscoped() IPasswordAuthDo {
	return p.withDO(p.DO.Unscoped())
}

func (p passwordAuthDo) Create(values ...*model.PasswordAuth) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p passwordAuthDo) CreateInBatches(values []*model.PasswordAuth, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p passwordAuthDo) Save(values ...*model.PasswordAuth) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p passwordAuthDo) First() (*model.PasswordAuth, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PasswordAuth), nil
	}
}

func (p passwordAuthDo) Take() (*model.PasswordAuth, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PasswordAuth), nil
	}
}

func (p passwordAuthDo) Last() (*model.PasswordAuth, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PasswordAuth), nil
	}
}

func (p passwordAuthDo) Find() ([]*model.PasswordAuth, error) {
	result, err := p.DO.Find()
	return result.([]*model.PasswordAuth), err
}

func (p passwordAuthDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PasswordAuth, err error) {
	buf := make([]*model.PasswordAuth, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p passwordAuthDo) FindInBatches(result *[]*model.PasswordAuth, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p passwordAuthDo) Attrs(attrs ...field.AssignExpr) IPasswordAuthDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p passwordAuthDo) Assign(attrs ...field.AssignExpr) IPasswordAuthDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p passwordAuthDo) Joins(fields ...field.RelationField) IPasswordAuthDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p passwordAuthDo) Preload(fields ...field.RelationField) IPasswordAuthDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p passwordAuthDo) FirstOrInit() (*model.PasswordAuth, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PasswordAuth), nil
	}
}

func (p passwordAuthDo) FirstOrCreate() (*model.PasswordAuth, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PasswordAuth), nil
	}
}

func (p passwordAuthDo) FindByPage(offset int, limit int) (result []*model.PasswordAuth, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p passwordAuthDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p passwordAuthDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p passwordAuthDo) Delete(models ...*model.PasswordAuth) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *passwordAuthDo) withDO(do gen.Dao) *passwordAuthDo {
	p.DO = *do.(*gen.DO)
	return p
}
