// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"hashnut-mpc-client/storage/dal/model"
)

func newReceiptAddress(db *gorm.DB, opts ...gen.DOOption) receiptAddress {
	_receiptAddress := receiptAddress{}

	_receiptAddress.receiptAddressDo.UseDB(db, opts...)
	_receiptAddress.receiptAddressDo.UseModel(&model.ReceiptAddress{})

	tableName := _receiptAddress.receiptAddressDo.TableName()
	_receiptAddress.ALL = field.NewAsterisk(tableName)
	_receiptAddress.Address = field.NewString(tableName, "address")
	_receiptAddress.Splitter = field.NewString(tableName, "splitter")
	_receiptAddress.Chain = field.NewString(tableName, "chain")
	_receiptAddress.Curve = field.NewString(tableName, "curve")
	_receiptAddress.KeyFromData = field.NewBytes(tableName, "key_from_data")
	_receiptAddress.PubKeyData = field.NewBytes(tableName, "pub_key_data")
	_receiptAddress.CreatedAt = field.NewTime(tableName, "created_at")
	_receiptAddress.UpdatedAt = field.NewTime(tableName, "updated_at")

	_receiptAddress.fillFieldMap()

	return _receiptAddress
}

type receiptAddress struct {
	receiptAddressDo receiptAddressDo

	ALL         field.Asterisk
	Address     field.String
	Splitter    field.String
	Chain       field.String
	Curve       field.String
	KeyFromData field.Bytes
	PubKeyData  field.Bytes
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (r receiptAddress) Table(newTableName string) *receiptAddress {
	r.receiptAddressDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r receiptAddress) As(alias string) *receiptAddress {
	r.receiptAddressDo.DO = *(r.receiptAddressDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *receiptAddress) updateTableName(table string) *receiptAddress {
	r.ALL = field.NewAsterisk(table)
	r.Address = field.NewString(table, "address")
	r.Splitter = field.NewString(table, "splitter")
	r.Chain = field.NewString(table, "chain")
	r.Curve = field.NewString(table, "curve")
	r.KeyFromData = field.NewBytes(table, "key_from_data")
	r.PubKeyData = field.NewBytes(table, "pub_key_data")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *receiptAddress) WithContext(ctx context.Context) IReceiptAddressDo {
	return r.receiptAddressDo.WithContext(ctx)
}

func (r receiptAddress) TableName() string { return r.receiptAddressDo.TableName() }

func (r receiptAddress) Alias() string { return r.receiptAddressDo.Alias() }

func (r receiptAddress) Columns(cols ...field.Expr) gen.Columns {
	return r.receiptAddressDo.Columns(cols...)
}

func (r *receiptAddress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *receiptAddress) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["address"] = r.Address
	r.fieldMap["splitter"] = r.Splitter
	r.fieldMap["chain"] = r.Chain
	r.fieldMap["curve"] = r.Curve
	r.fieldMap["key_from_data"] = r.KeyFromData
	r.fieldMap["pub_key_data"] = r.PubKeyData
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r receiptAddress) clone(db *gorm.DB) receiptAddress {
	r.receiptAddressDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r receiptAddress) replaceDB(db *gorm.DB) receiptAddress {
	r.receiptAddressDo.ReplaceDB(db)
	return r
}

type receiptAddressDo struct{ gen.DO }

type IReceiptAddressDo interface {
	gen.SubQuery
	Debug() IReceiptAddressDo
	WithContext(ctx context.Context) IReceiptAddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReceiptAddressDo
	WriteDB() IReceiptAddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReceiptAddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReceiptAddressDo
	Not(conds ...gen.Condition) IReceiptAddressDo
	Or(conds ...gen.Condition) IReceiptAddressDo
	Select(conds ...field.Expr) IReceiptAddressDo
	Where(conds ...gen.Condition) IReceiptAddressDo
	Order(conds ...field.Expr) IReceiptAddressDo
	Distinct(cols ...field.Expr) IReceiptAddressDo
	Omit(cols ...field.Expr) IReceiptAddressDo
	Join(table schema.Tabler, on ...field.Expr) IReceiptAddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReceiptAddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReceiptAddressDo
	Group(cols ...field.Expr) IReceiptAddressDo
	Having(conds ...gen.Condition) IReceiptAddressDo
	Limit(limit int) IReceiptAddressDo
	Offset(offset int) IReceiptAddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReceiptAddressDo
	Unscoped() IReceiptAddressDo
	Create(values ...*model.ReceiptAddress) error
	CreateInBatches(values []*model.ReceiptAddress, batchSize int) error
	Save(values ...*model.ReceiptAddress) error
	First() (*model.ReceiptAddress, error)
	Take() (*model.ReceiptAddress, error)
	Last() (*model.ReceiptAddress, error)
	Find() ([]*model.ReceiptAddress, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReceiptAddress, err error)
	FindInBatches(result *[]*model.ReceiptAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ReceiptAddress) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReceiptAddressDo
	Assign(attrs ...field.AssignExpr) IReceiptAddressDo
	Joins(fields ...field.RelationField) IReceiptAddressDo
	Preload(fields ...field.RelationField) IReceiptAddressDo
	FirstOrInit() (*model.ReceiptAddress, error)
	FirstOrCreate() (*model.ReceiptAddress, error)
	FindByPage(offset int, limit int) (result []*model.ReceiptAddress, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReceiptAddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r receiptAddressDo) Debug() IReceiptAddressDo {
	return r.withDO(r.DO.Debug())
}

func (r receiptAddressDo) WithContext(ctx context.Context) IReceiptAddressDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r receiptAddressDo) ReadDB() IReceiptAddressDo {
	return r.Clauses(dbresolver.Read)
}

func (r receiptAddressDo) WriteDB() IReceiptAddressDo {
	return r.Clauses(dbresolver.Write)
}

func (r receiptAddressDo) Session(config *gorm.Session) IReceiptAddressDo {
	return r.withDO(r.DO.Session(config))
}

func (r receiptAddressDo) Clauses(conds ...clause.Expression) IReceiptAddressDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r receiptAddressDo) Returning(value interface{}, columns ...string) IReceiptAddressDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r receiptAddressDo) Not(conds ...gen.Condition) IReceiptAddressDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r receiptAddressDo) Or(conds ...gen.Condition) IReceiptAddressDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r receiptAddressDo) Select(conds ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r receiptAddressDo) Where(conds ...gen.Condition) IReceiptAddressDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r receiptAddressDo) Order(conds ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r receiptAddressDo) Distinct(cols ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r receiptAddressDo) Omit(cols ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r receiptAddressDo) Join(table schema.Tabler, on ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r receiptAddressDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r receiptAddressDo) RightJoin(table schema.Tabler, on ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r receiptAddressDo) Group(cols ...field.Expr) IReceiptAddressDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r receiptAddressDo) Having(conds ...gen.Condition) IReceiptAddressDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r receiptAddressDo) Limit(limit int) IReceiptAddressDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r receiptAddressDo) Offset(offset int) IReceiptAddressDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r receiptAddressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReceiptAddressDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r receiptAddressDo) Unscoped() IReceiptAddressDo {
	return r.withDO(r.DO.Unscoped())
}

func (r receiptAddressDo) Create(values ...*model.ReceiptAddress) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r receiptAddressDo) CreateInBatches(values []*model.ReceiptAddress, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r receiptAddressDo) Save(values ...*model.ReceiptAddress) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r receiptAddressDo) First() (*model.ReceiptAddress, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptAddress), nil
	}
}

func (r receiptAddressDo) Take() (*model.ReceiptAddress, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptAddress), nil
	}
}

func (r receiptAddressDo) Last() (*model.ReceiptAddress, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptAddress), nil
	}
}

func (r receiptAddressDo) Find() ([]*model.ReceiptAddress, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReceiptAddress), err
}

func (r receiptAddressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReceiptAddress, err error) {
	buf := make([]*model.ReceiptAddress, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r receiptAddressDo) FindInBatches(result *[]*model.ReceiptAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r receiptAddressDo) Attrs(attrs ...field.AssignExpr) IReceiptAddressDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r receiptAddressDo) Assign(attrs ...field.AssignExpr) IReceiptAddressDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r receiptAddressDo) Joins(fields ...field.RelationField) IReceiptAddressDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r receiptAddressDo) Preload(fields ...field.RelationField) IReceiptAddressDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r receiptAddressDo) FirstOrInit() (*model.ReceiptAddress, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptAddress), nil
	}
}

func (r receiptAddressDo) FirstOrCreate() (*model.ReceiptAddress, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReceiptAddress), nil
	}
}

func (r receiptAddressDo) FindByPage(offset int, limit int) (result []*model.ReceiptAddress, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r receiptAddressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r receiptAddressDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r receiptAddressDo) Delete(models ...*model.ReceiptAddress) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *receiptAddressDo) withDO(do gen.Dao) *receiptAddressDo {
	r.DO = *do.(*gen.DO)
	return r
}
