// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"hashnut-mpc-client/storage/dal/model"
)

func newRPCEndpoint(db *gorm.DB, opts ...gen.DOOption) rPCEndpoint {
	_rPCEndpoint := rPCEndpoint{}

	_rPCEndpoint.rPCEndpointDo.UseDB(db, opts...)
	_rPCEndpoint.rPCEndpointDo.UseModel(&model.RPCEndpoint{})

	tableName := _rPCEndpoint.rPCEndpointDo.TableName()
	_rPCEndpoint.ALL = field.NewAsterisk(tableName)
	_rPCEndpoint.Chain = field.NewString(tableName, "chain")
	_rPCEndpoint.Endpoint = field.NewString(tableName, "endpoint")
	_rPCEndpoint.APIKey = field.NewString(tableName, "api_key")
	_rPCEndpoint.CreatedAt = field.NewTime(tableName, "created_at")
	_rPCEndpoint.UpdatedAt = field.NewTime(tableName, "updated_at")

	_rPCEndpoint.fillFieldMap()

	return _rPCEndpoint
}

type rPCEndpoint struct {
	rPCEndpointDo rPCEndpointDo

	ALL       field.Asterisk
	Chain     field.String
	Endpoint  field.String
	APIKey    field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r rPCEndpoint) Table(newTableName string) *rPCEndpoint {
	r.rPCEndpointDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rPCEndpoint) As(alias string) *rPCEndpoint {
	r.rPCEndpointDo.DO = *(r.rPCEndpointDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rPCEndpoint) updateTableName(table string) *rPCEndpoint {
	r.ALL = field.NewAsterisk(table)
	r.Chain = field.NewString(table, "chain")
	r.Endpoint = field.NewString(table, "endpoint")
	r.APIKey = field.NewString(table, "api_key")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *rPCEndpoint) WithContext(ctx context.Context) IRPCEndpointDo {
	return r.rPCEndpointDo.WithContext(ctx)
}

func (r rPCEndpoint) TableName() string { return r.rPCEndpointDo.TableName() }

func (r rPCEndpoint) Alias() string { return r.rPCEndpointDo.Alias() }

func (r rPCEndpoint) Columns(cols ...field.Expr) gen.Columns { return r.rPCEndpointDo.Columns(cols...) }

func (r *rPCEndpoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rPCEndpoint) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["chain"] = r.Chain
	r.fieldMap["endpoint"] = r.Endpoint
	r.fieldMap["api_key"] = r.APIKey
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r rPCEndpoint) clone(db *gorm.DB) rPCEndpoint {
	r.rPCEndpointDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rPCEndpoint) replaceDB(db *gorm.DB) rPCEndpoint {
	r.rPCEndpointDo.ReplaceDB(db)
	return r
}

type rPCEndpointDo struct{ gen.DO }

type IRPCEndpointDo interface {
	gen.SubQuery
	Debug() IRPCEndpointDo
	WithContext(ctx context.Context) IRPCEndpointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRPCEndpointDo
	WriteDB() IRPCEndpointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRPCEndpointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRPCEndpointDo
	Not(conds ...gen.Condition) IRPCEndpointDo
	Or(conds ...gen.Condition) IRPCEndpointDo
	Select(conds ...field.Expr) IRPCEndpointDo
	Where(conds ...gen.Condition) IRPCEndpointDo
	Order(conds ...field.Expr) IRPCEndpointDo
	Distinct(cols ...field.Expr) IRPCEndpointDo
	Omit(cols ...field.Expr) IRPCEndpointDo
	Join(table schema.Tabler, on ...field.Expr) IRPCEndpointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRPCEndpointDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRPCEndpointDo
	Group(cols ...field.Expr) IRPCEndpointDo
	Having(conds ...gen.Condition) IRPCEndpointDo
	Limit(limit int) IRPCEndpointDo
	Offset(offset int) IRPCEndpointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRPCEndpointDo
	Unscoped() IRPCEndpointDo
	Create(values ...*model.RPCEndpoint) error
	CreateInBatches(values []*model.RPCEndpoint, batchSize int) error
	Save(values ...*model.RPCEndpoint) error
	First() (*model.RPCEndpoint, error)
	Take() (*model.RPCEndpoint, error)
	Last() (*model.RPCEndpoint, error)
	Find() ([]*model.RPCEndpoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RPCEndpoint, err error)
	FindInBatches(result *[]*model.RPCEndpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RPCEndpoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRPCEndpointDo
	Assign(attrs ...field.AssignExpr) IRPCEndpointDo
	Joins(fields ...field.RelationField) IRPCEndpointDo
	Preload(fields ...field.RelationField) IRPCEndpointDo
	FirstOrInit() (*model.RPCEndpoint, error)
	FirstOrCreate() (*model.RPCEndpoint, error)
	FindByPage(offset int, limit int) (result []*model.RPCEndpoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRPCEndpointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rPCEndpointDo) Debug() IRPCEndpointDo {
	return r.withDO(r.DO.Debug())
}

func (r rPCEndpointDo) WithContext(ctx context.Context) IRPCEndpointDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rPCEndpointDo) ReadDB() IRPCEndpointDo {
	return r.Clauses(dbresolver.Read)
}

func (r rPCEndpointDo) WriteDB() IRPCEndpointDo {
	return r.Clauses(dbresolver.Write)
}

func (r rPCEndpointDo) Session(config *gorm.Session) IRPCEndpointDo {
	return r.withDO(r.DO.Session(config))
}

func (r rPCEndpointDo) Clauses(conds ...clause.Expression) IRPCEndpointDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rPCEndpointDo) Returning(value interface{}, columns ...string) IRPCEndpointDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rPCEndpointDo) Not(conds ...gen.Condition) IRPCEndpointDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rPCEndpointDo) Or(conds ...gen.Condition) IRPCEndpointDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rPCEndpointDo) Select(conds ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rPCEndpointDo) Where(conds ...gen.Condition) IRPCEndpointDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rPCEndpointDo) Order(conds ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rPCEndpointDo) Distinct(cols ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rPCEndpointDo) Omit(cols ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rPCEndpointDo) Join(table schema.Tabler, on ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rPCEndpointDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rPCEndpointDo) RightJoin(table schema.Tabler, on ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rPCEndpointDo) Group(cols ...field.Expr) IRPCEndpointDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rPCEndpointDo) Having(conds ...gen.Condition) IRPCEndpointDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rPCEndpointDo) Limit(limit int) IRPCEndpointDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rPCEndpointDo) Offset(offset int) IRPCEndpointDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rPCEndpointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRPCEndpointDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rPCEndpointDo) Unscoped() IRPCEndpointDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rPCEndpointDo) Create(values ...*model.RPCEndpoint) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rPCEndpointDo) CreateInBatches(values []*model.RPCEndpoint, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rPCEndpointDo) Save(values ...*model.RPCEndpoint) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rPCEndpointDo) First() (*model.RPCEndpoint, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RPCEndpoint), nil
	}
}

func (r rPCEndpointDo) Take() (*model.RPCEndpoint, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RPCEndpoint), nil
	}
}

func (r rPCEndpointDo) Last() (*model.RPCEndpoint, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RPCEndpoint), nil
	}
}

func (r rPCEndpointDo) Find() ([]*model.RPCEndpoint, error) {
	result, err := r.DO.Find()
	return result.([]*model.RPCEndpoint), err
}

func (r rPCEndpointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RPCEndpoint, err error) {
	buf := make([]*model.RPCEndpoint, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rPCEndpointDo) FindInBatches(result *[]*model.RPCEndpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rPCEndpointDo) Attrs(attrs ...field.AssignExpr) IRPCEndpointDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rPCEndpointDo) Assign(attrs ...field.AssignExpr) IRPCEndpointDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rPCEndpointDo) Joins(fields ...field.RelationField) IRPCEndpointDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rPCEndpointDo) Preload(fields ...field.RelationField) IRPCEndpointDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rPCEndpointDo) FirstOrInit() (*model.RPCEndpoint, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RPCEndpoint), nil
	}
}

func (r rPCEndpointDo) FirstOrCreate() (*model.RPCEndpoint, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RPCEndpoint), nil
	}
}

func (r rPCEndpointDo) FindByPage(offset int, limit int) (result []*model.RPCEndpoint, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rPCEndpointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rPCEndpointDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rPCEndpointDo) Delete(models ...*model.RPCEndpoint) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rPCEndpointDo) withDO(do gen.Dao) *rPCEndpointDo {
	r.DO = *do.(*gen.DO)
	return r
}
