// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"hashnut-mpc-client/storage/dal/model"
)

func newSplitWallet(db *gorm.DB, opts ...gen.DOOption) splitWallet {
	_splitWallet := splitWallet{}

	_splitWallet.splitWalletDo.UseDB(db, opts...)
	_splitWallet.splitWalletDo.UseModel(&model.SplitWallet{})

	tableName := _splitWallet.splitWalletDo.TableName()
	_splitWallet.ALL = field.NewAsterisk(tableName)
	_splitWallet.Address = field.NewString(tableName, "address")
	_splitWallet.Chain = field.NewString(tableName, "chain")
	_splitWallet.Merchant = field.NewString(tableName, "merchant")
	_splitWallet.CreatedAt = field.NewTime(tableName, "created_at")
	_splitWallet.UpdatedAt = field.NewTime(tableName, "updated_at")

	_splitWallet.fillFieldMap()

	return _splitWallet
}

type splitWallet struct {
	splitWalletDo splitWalletDo

	ALL       field.Asterisk
	Address   field.String
	Chain     field.String
	Merchant  field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (s splitWallet) Table(newTableName string) *splitWallet {
	s.splitWalletDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s splitWallet) As(alias string) *splitWallet {
	s.splitWalletDo.DO = *(s.splitWalletDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *splitWallet) updateTableName(table string) *splitWallet {
	s.ALL = field.NewAsterisk(table)
	s.Address = field.NewString(table, "address")
	s.Chain = field.NewString(table, "chain")
	s.Merchant = field.NewString(table, "merchant")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *splitWallet) WithContext(ctx context.Context) ISplitWalletDo {
	return s.splitWalletDo.WithContext(ctx)
}

func (s splitWallet) TableName() string { return s.splitWalletDo.TableName() }

func (s splitWallet) Alias() string { return s.splitWalletDo.Alias() }

func (s splitWallet) Columns(cols ...field.Expr) gen.Columns { return s.splitWalletDo.Columns(cols...) }

func (s *splitWallet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *splitWallet) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["address"] = s.Address
	s.fieldMap["chain"] = s.Chain
	s.fieldMap["merchant"] = s.Merchant
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s splitWallet) clone(db *gorm.DB) splitWallet {
	s.splitWalletDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s splitWallet) replaceDB(db *gorm.DB) splitWallet {
	s.splitWalletDo.ReplaceDB(db)
	return s
}

type splitWalletDo struct{ gen.DO }

type ISplitWalletDo interface {
	gen.SubQuery
	Debug() ISplitWalletDo
	WithContext(ctx context.Context) ISplitWalletDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISplitWalletDo
	WriteDB() ISplitWalletDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISplitWalletDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISplitWalletDo
	Not(conds ...gen.Condition) ISplitWalletDo
	Or(conds ...gen.Condition) ISplitWalletDo
	Select(conds ...field.Expr) ISplitWalletDo
	Where(conds ...gen.Condition) ISplitWalletDo
	Order(conds ...field.Expr) ISplitWalletDo
	Distinct(cols ...field.Expr) ISplitWalletDo
	Omit(cols ...field.Expr) ISplitWalletDo
	Join(table schema.Tabler, on ...field.Expr) ISplitWalletDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISplitWalletDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISplitWalletDo
	Group(cols ...field.Expr) ISplitWalletDo
	Having(conds ...gen.Condition) ISplitWalletDo
	Limit(limit int) ISplitWalletDo
	Offset(offset int) ISplitWalletDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISplitWalletDo
	Unscoped() ISplitWalletDo
	Create(values ...*model.SplitWallet) error
	CreateInBatches(values []*model.SplitWallet, batchSize int) error
	Save(values ...*model.SplitWallet) error
	First() (*model.SplitWallet, error)
	Take() (*model.SplitWallet, error)
	Last() (*model.SplitWallet, error)
	Find() ([]*model.SplitWallet, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SplitWallet, err error)
	FindInBatches(result *[]*model.SplitWallet, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SplitWallet) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISplitWalletDo
	Assign(attrs ...field.AssignExpr) ISplitWalletDo
	Joins(fields ...field.RelationField) ISplitWalletDo
	Preload(fields ...field.RelationField) ISplitWalletDo
	FirstOrInit() (*model.SplitWallet, error)
	FirstOrCreate() (*model.SplitWallet, error)
	FindByPage(offset int, limit int) (result []*model.SplitWallet, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISplitWalletDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s splitWalletDo) Debug() ISplitWalletDo {
	return s.withDO(s.DO.Debug())
}

func (s splitWalletDo) WithContext(ctx context.Context) ISplitWalletDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s splitWalletDo) ReadDB() ISplitWalletDo {
	return s.Clauses(dbresolver.Read)
}

func (s splitWalletDo) WriteDB() ISplitWalletDo {
	return s.Clauses(dbresolver.Write)
}

func (s splitWalletDo) Session(config *gorm.Session) ISplitWalletDo {
	return s.withDO(s.DO.Session(config))
}

func (s splitWalletDo) Clauses(conds ...clause.Expression) ISplitWalletDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s splitWalletDo) Returning(value interface{}, columns ...string) ISplitWalletDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s splitWalletDo) Not(conds ...gen.Condition) ISplitWalletDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s splitWalletDo) Or(conds ...gen.Condition) ISplitWalletDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s splitWalletDo) Select(conds ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s splitWalletDo) Where(conds ...gen.Condition) ISplitWalletDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s splitWalletDo) Order(conds ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s splitWalletDo) Distinct(cols ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s splitWalletDo) Omit(cols ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s splitWalletDo) Join(table schema.Tabler, on ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s splitWalletDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s splitWalletDo) RightJoin(table schema.Tabler, on ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s splitWalletDo) Group(cols ...field.Expr) ISplitWalletDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s splitWalletDo) Having(conds ...gen.Condition) ISplitWalletDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s splitWalletDo) Limit(limit int) ISplitWalletDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s splitWalletDo) Offset(offset int) ISplitWalletDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s splitWalletDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISplitWalletDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s splitWalletDo) Unscoped() ISplitWalletDo {
	return s.withDO(s.DO.Unscoped())
}

func (s splitWalletDo) Create(values ...*model.SplitWallet) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s splitWalletDo) CreateInBatches(values []*model.SplitWallet, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s splitWalletDo) Save(values ...*model.SplitWallet) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s splitWalletDo) First() (*model.SplitWallet, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SplitWallet), nil
	}
}

func (s splitWalletDo) Take() (*model.SplitWallet, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SplitWallet), nil
	}
}

func (s splitWalletDo) Last() (*model.SplitWallet, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SplitWallet), nil
	}
}

func (s splitWalletDo) Find() ([]*model.SplitWallet, error) {
	result, err := s.DO.Find()
	return result.([]*model.SplitWallet), err
}

func (s splitWalletDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SplitWallet, err error) {
	buf := make([]*model.SplitWallet, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s splitWalletDo) FindInBatches(result *[]*model.SplitWallet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s splitWalletDo) Attrs(attrs ...field.AssignExpr) ISplitWalletDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s splitWalletDo) Assign(attrs ...field.AssignExpr) ISplitWalletDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s splitWalletDo) Joins(fields ...field.RelationField) ISplitWalletDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s splitWalletDo) Preload(fields ...field.RelationField) ISplitWalletDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s splitWalletDo) FirstOrInit() (*model.SplitWallet, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SplitWallet), nil
	}
}

func (s splitWalletDo) FirstOrCreate() (*model.SplitWallet, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SplitWallet), nil
	}
}

func (s splitWalletDo) FindByPage(offset int, limit int) (result []*model.SplitWallet, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s splitWalletDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s splitWalletDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s splitWalletDo) Delete(models ...*model.SplitWallet) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *splitWalletDo) withDO(do gen.Dao) *splitWalletDo {
	s.DO = *do.(*gen.DO)
	return s
}
