// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"hashnut-mpc-client/storage/dal/model"
)

func newTokenConfig(db *gorm.DB, opts ...gen.DOOption) tokenConfig {
	_tokenConfig := tokenConfig{}

	_tokenConfig.tokenConfigDo.UseDB(db, opts...)
	_tokenConfig.tokenConfigDo.UseModel(&model.TokenConfig{})

	tableName := _tokenConfig.tokenConfigDo.TableName()
	_tokenConfig.ALL = field.NewAsterisk(tableName)
	_tokenConfig.Symbol = field.NewString(tableName, "symbol")
	_tokenConfig.Chain = field.NewString(tableName, "chain")
	_tokenConfig.Contract = field.NewString(tableName, "contract")
	_tokenConfig.Name = field.NewString(tableName, "name")
	_tokenConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_tokenConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tokenConfig.fillFieldMap()

	return _tokenConfig
}

type tokenConfig struct {
	tokenConfigDo tokenConfigDo

	ALL       field.Asterisk
	Symbol    field.String
	Chain     field.String
	Contract  field.String
	Name      field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t tokenConfig) Table(newTableName string) *tokenConfig {
	t.tokenConfigDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tokenConfig) As(alias string) *tokenConfig {
	t.tokenConfigDo.DO = *(t.tokenConfigDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tokenConfig) updateTableName(table string) *tokenConfig {
	t.ALL = field.NewAsterisk(table)
	t.Symbol = field.NewString(table, "symbol")
	t.Chain = field.NewString(table, "chain")
	t.Contract = field.NewString(table, "contract")
	t.Name = field.NewString(table, "name")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tokenConfig) WithContext(ctx context.Context) ITokenConfigDo {
	return t.tokenConfigDo.WithContext(ctx)
}

func (t tokenConfig) TableName() string { return t.tokenConfigDo.TableName() }

func (t tokenConfig) Alias() string { return t.tokenConfigDo.Alias() }

func (t tokenConfig) Columns(cols ...field.Expr) gen.Columns { return t.tokenConfigDo.Columns(cols...) }

func (t *tokenConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tokenConfig) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["symbol"] = t.Symbol
	t.fieldMap["chain"] = t.Chain
	t.fieldMap["contract"] = t.Contract
	t.fieldMap["name"] = t.Name
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tokenConfig) clone(db *gorm.DB) tokenConfig {
	t.tokenConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tokenConfig) replaceDB(db *gorm.DB) tokenConfig {
	t.tokenConfigDo.ReplaceDB(db)
	return t
}

type tokenConfigDo struct{ gen.DO }

type ITokenConfigDo interface {
	gen.SubQuery
	Debug() ITokenConfigDo
	WithContext(ctx context.Context) ITokenConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITokenConfigDo
	WriteDB() ITokenConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITokenConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITokenConfigDo
	Not(conds ...gen.Condition) ITokenConfigDo
	Or(conds ...gen.Condition) ITokenConfigDo
	Select(conds ...field.Expr) ITokenConfigDo
	Where(conds ...gen.Condition) ITokenConfigDo
	Order(conds ...field.Expr) ITokenConfigDo
	Distinct(cols ...field.Expr) ITokenConfigDo
	Omit(cols ...field.Expr) ITokenConfigDo
	Join(table schema.Tabler, on ...field.Expr) ITokenConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITokenConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITokenConfigDo
	Group(cols ...field.Expr) ITokenConfigDo
	Having(conds ...gen.Condition) ITokenConfigDo
	Limit(limit int) ITokenConfigDo
	Offset(offset int) ITokenConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITokenConfigDo
	Unscoped() ITokenConfigDo
	Create(values ...*model.TokenConfig) error
	CreateInBatches(values []*model.TokenConfig, batchSize int) error
	Save(values ...*model.TokenConfig) error
	First() (*model.TokenConfig, error)
	Take() (*model.TokenConfig, error)
	Last() (*model.TokenConfig, error)
	Find() ([]*model.TokenConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TokenConfig, err error)
	FindInBatches(result *[]*model.TokenConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TokenConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITokenConfigDo
	Assign(attrs ...field.AssignExpr) ITokenConfigDo
	Joins(fields ...field.RelationField) ITokenConfigDo
	Preload(fields ...field.RelationField) ITokenConfigDo
	FirstOrInit() (*model.TokenConfig, error)
	FirstOrCreate() (*model.TokenConfig, error)
	FindByPage(offset int, limit int) (result []*model.TokenConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITokenConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tokenConfigDo) Debug() ITokenConfigDo {
	return t.withDO(t.DO.Debug())
}

func (t tokenConfigDo) WithContext(ctx context.Context) ITokenConfigDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tokenConfigDo) ReadDB() ITokenConfigDo {
	return t.Clauses(dbresolver.Read)
}

func (t tokenConfigDo) WriteDB() ITokenConfigDo {
	return t.Clauses(dbresolver.Write)
}

func (t tokenConfigDo) Session(config *gorm.Session) ITokenConfigDo {
	return t.withDO(t.DO.Session(config))
}

func (t tokenConfigDo) Clauses(conds ...clause.Expression) ITokenConfigDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tokenConfigDo) Returning(value interface{}, columns ...string) ITokenConfigDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tokenConfigDo) Not(conds ...gen.Condition) ITokenConfigDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tokenConfigDo) Or(conds ...gen.Condition) ITokenConfigDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tokenConfigDo) Select(conds ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tokenConfigDo) Where(conds ...gen.Condition) ITokenConfigDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tokenConfigDo) Order(conds ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tokenConfigDo) Distinct(cols ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tokenConfigDo) Omit(cols ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tokenConfigDo) Join(table schema.Tabler, on ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tokenConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tokenConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tokenConfigDo) Group(cols ...field.Expr) ITokenConfigDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tokenConfigDo) Having(conds ...gen.Condition) ITokenConfigDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tokenConfigDo) Limit(limit int) ITokenConfigDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tokenConfigDo) Offset(offset int) ITokenConfigDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tokenConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITokenConfigDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tokenConfigDo) Unscoped() ITokenConfigDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tokenConfigDo) Create(values ...*model.TokenConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tokenConfigDo) CreateInBatches(values []*model.TokenConfig, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tokenConfigDo) Save(values ...*model.TokenConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tokenConfigDo) First() (*model.TokenConfig, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenConfig), nil
	}
}

func (t tokenConfigDo) Take() (*model.TokenConfig, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenConfig), nil
	}
}

func (t tokenConfigDo) Last() (*model.TokenConfig, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenConfig), nil
	}
}

func (t tokenConfigDo) Find() ([]*model.TokenConfig, error) {
	result, err := t.DO.Find()
	return result.([]*model.TokenConfig), err
}

func (t tokenConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TokenConfig, err error) {
	buf := make([]*model.TokenConfig, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tokenConfigDo) FindInBatches(result *[]*model.TokenConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tokenConfigDo) Attrs(attrs ...field.AssignExpr) ITokenConfigDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tokenConfigDo) Assign(attrs ...field.AssignExpr) ITokenConfigDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tokenConfigDo) Joins(fields ...field.RelationField) ITokenConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tokenConfigDo) Preload(fields ...field.RelationField) ITokenConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tokenConfigDo) FirstOrInit() (*model.TokenConfig, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenConfig), nil
	}
}

func (t tokenConfigDo) FirstOrCreate() (*model.TokenConfig, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenConfig), nil
	}
}

func (t tokenConfigDo) FindByPage(offset int, limit int) (result []*model.TokenConfig, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tokenConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tokenConfigDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tokenConfigDo) Delete(models ...*model.TokenConfig) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tokenConfigDo) withDO(do gen.Dao) *tokenConfigDo {
	t.DO = *do.(*gen.DO)
	return t
}
